# 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 #
# 💥                                                                        💥 #
# 💥 Do not edit this file as it will be overwritten!                       💥 #
# 💥                                                                        💥 #
# 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 #

# See: https://www.terraform.io/docs/backends/types/s3.html
# unfortunately no interpolation
terraform {
  backend "s3" {
    bucket  = "gruenehoelle-tf-state"
    key     = "dgh-jbl-chat/terraform.tfstate"
    region  = "eu-west-2"
    profile = "gruenehoelle"

    encrypt    = true
    kms_key_id = "alias/main"

    dynamodb_table = "gruenehoelle-tf-state"

    max_retries = 10
  }
}

variable "app_name" {
  default = "dgh-jbl-chat"
}
