# 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 #
# 💥                                                                        💥 #
# 💥 Do not edit this file as it will be overwritten!                       💥 #
# 💥                                                                        💥 #
# 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 #

terraform {
  required_version = "1.2.9"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.34.0"
    }

    random = {
      source  = "hashicorp/random"
      version = "3.4.3"
    }

    null = {
      source  = "hashicorp/null"
      version = "3.1.1"
    }

    docker = {
      source  = "kreuzwerker/docker"
      version = "2.22.0"
    }

    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "3.25.0"
    }

    dns = {
      source  = "hashicorp/dns"
      version = "3.2.3"
    }

    archive = {
      source  = "hashicorp/archive"
      version = "2.2.0"
    }
  }
}

provider "aws" {
  region  = var.aws_region
  profile = "gruenehoelle"

  default_tags {
    tags = local.tags
  }
}

provider "aws" {
  alias = "ireland"

  region  = "eu-west-1"
  profile = "gruenehoelle"

  default_tags {
    tags = local.tags
  }
}

data "aws_caller_identity" "current" {}

data "aws_region" "current" {}

data "aws_availability_zones" "available" {}

provider "cloudflare" {
  account_id = var.cloudflare_account_id
}

provider "random" {
}


provider "null" {
}

provider "docker" {
}

provider "dns" {
}

provider "archive" {
}
