# 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 #
# 💥                                                                        💥 #
# 💥 Do not edit this file as it will be overwritten!                       💥 #
# 💥                                                                        💥 #
# 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 #

variable "aws_region" {
  type    = string
  default = "eu-west-2"
}

variable "cloudflare_account_id" {
  type    = string
  default = null
}

variable "docker_cert_path" {
  type    = string
  default = null
}

variable "docker_username" {
  description = "Docker registry username."
  type        = string
  default     = null
}

variable "docker_password" {
  description = "Docker registry password."
  type        = string
  default     = null
}

variable "docker_image_tag" {
  description = "Docker image version."
  type        = string
  default     = "latest"
}

locals {
  aws_current_account = data.aws_caller_identity.current.account_id
  aws_current_region  = data.aws_region.current.name
}
